### ISSUE TITLE
the multigpu training is 4 times slower

### ISSUE THREAD

**Issue by shamsbasir** [pytorch/examples#1085] opened 2022-10-18 16:19 UTC
Hi @suraj813, 

I used your tutorial codes to experiment with distributed training. My training time for 1 epoch with multigpu_torchrun.py 
is 4 times slower than the single_gpu.py . I experimented with multiple batchsizes and large training size as well as large network to make sure the communication overhead is not higher than the computation. 
could you please point me to what could possibly be the issue ?

Thanks

**Comment by suraj813** [comment] 2022-11-15 16:55
Duplicate of https://github.com/pytorch/tutorials/issues/2114

**Closed by suraj813** 2022-11-15 16:55 UTC
