### ISSUE TITLE
How large batch size should I set for imagenet training

### ISSUE THREAD

**Issue by lith0613** [pytorch/examples#393] opened 2018-07-26 02:51 UTC
I just use the default setting of batch size 256 and 8 TiTAN XP gpus on resnet34， it takes about 1.5 hours for one epoch, I want to speed up the training process,  Can I increase the batch size ?

**Comment by soumith** [comment] 2018-07-27 04:04
duplicate of the same issue on pytorch/pytorch

**Closed by soumith** 2018-07-27 04:04 UTC
