### ISSUE TITLE
parameter server example not running in ubuntu

### ISSUE THREAD

**Issue by gagandeep987123** [pytorch/examples#1023] opened 2022-07-14 13:22 UTC
I am running the server and worker in separate sessions but execution stalls in the worker thread at line 175 while running 
`    for i, (data, target) in enumerate(train_loader):
`
However, it is running fine on Mac. 
The issue only happens in ubuntu.
Can you please help

**Comment by hudeven** [comment] 2022-07-18 18:48
@gagandeep987123 thanks for reporting the issue! It seems to be deadlock caused by "fork" start method(default in Linux). In Mac, the default is "spawn" so it works fine. You could try to add "mp.set_start_method("spawn")" before any process starts.

**Comment by hudeven** [comment] 2022-07-28 21:39
@gagandeep987123 Please feel free to reopen this issue if it's not resolved by https://github.com/pytorch/examples/pull/1025

**Closed by hudeven** 2022-07-28 21:39 UTC
Labels: bug, distributed
